# This is a basic workflow to help you get started with Actions

name: React to Surge CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - run: echo "Installing Node.js..."
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12
      
      - run: echo "Installing project dependencies using Yarn (yarn install...)"
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command
      
      
      - name: Build React App
        run: |
          echo "Creating a production build using Yarn (yarn build...)"
          yarn build
        env: 
            CI: false
      
      - name: Install Surge
        run: |
          echo "Installing surge"
          npm install --global surge
      
      - name: Deploy to Surge
        run: |
          echo "Deploying to surge..."
          surge ./build ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
          echo "Congratulations! Your app is deployed, visit your app ${{ secrets.SURGE_DOMAIN }}





        
